### ISSUE TITLE
Source file types

### ISSUE THREAD

**Issue by chrissearle** [petergeneric/unifi-protect-remux#10]
Not really an issue - just curiosity :)

I know the readme states "primarily designed to work on "0_rotating" .ubv files" - but - I was digging around in my CK2+ and I noted that in the same location I had both 0_rotating and also 2_rotating files.

Not exactly finding much via google - just curious if you have come across any info on the difference (as in - should I be ignoring them, or adding them to the find clause of my current script) ?

**Comment by petergeneric** [comment]
I should really have an outline wiki page that gives some info on what the different files are...

The 2_rotating .ubv files are low-res low-bitrate camera feeds (and since they obey the same size limit config value, they cover a longer stretch of time than the full-res files).

The reason for that note is really to keep the scope of this project constrained - I don't want to have people depending on the tool working for the ancillary files just in case Ubiquiti makes a change such that they're no longer similar in structure to the 0_rotating files in the future (e.g. the timelapse files are way messier with lots of partitions).

The tool actually does work fine for 2_rotating files (and on the files in /srv/unifi-protect/temp). If somebody had a use-case that involved these files then I'd certainly be open to supporting them if their structure varies from the 0_rotating structure in the future.

**Comment by chrissearle** [comment]
That's useful to know

Right now I'm taking all Ung in video except pool.

I will easily drop the 2_ files now. Probably keep the time lapse ones. 

But it was all based on guesswork - pool looked too unstructured.

Plan is a cron job on the ck2 just running the ubvinfo step - will be called prior to rsync to a NAS with remux on it - also called by a cron job. 

Just trying to get it to be the most interesting files without too much extra.
