### ISSUE TITLE
Does this solution work on MacOS?

### ISSUE THREAD

**Issue by miller0929** [petergeneric/unifi-protect-remux#11]

**Comment by petergeneric** [comment]
Hi,

The extraction and remux process itself will run on macOS, but you'll need to run a preparation step on Ubiquiti hardware (or on a Linux machine or VM) first to generate a .txt file describing the contents of the .ubv video file.

Have a look at https://github.com/petergeneric/unifi-protect-remux#run-ubvinfo-remotely-and-remux-locally to show how to generate a .txt file alongside the .ubv files, if you transfer that .txt and the .ubv to your mac then it should run fine.

You'll also need FFmpeg, "brew install ffmpeg" if you have homebrew, otherwise you can find ffmpeg static binaries here: https://evermeet.cx/ffmpeg/

You'll find binaries for macOS x86 on the releases page, https://github.com/petergeneric/unifi-protect-remux/releases

I don't have an M1 build available, but I would expect the x86 binary to run well under Rosetta 2.

**Comment by miller0929** [comment]
Hi, I put the prepare.sh in the video folder on the cloud key gen 2 plus, right next to the .ubv files. I gave the sh file +x as well. When I run ./prepare.sh F09FC213B2D2_0_rotating_1620810935690.ubv, I got the following error:
./prepare.sh: line 7: syntax error near unexpected token `newline'
./prepare.sh: line 7: `<!DOCTYPE html>'
Any ideas?

**Comment by petergeneric** [comment]
Strangely, I'm not able to reproduce that on my cloudkey gen2+, could you run md5sum prepare.sh? Here's what I get:

```cc47c581190b3c14ac2675a708c8358b  prepare.sh```

Alternatively, you'll see prepare.sh is actually quite simple - it's running the following command against each .ubv you pass it - so you could always try running this command manually:
```/usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo -P -f "file.ubv" > "file.ubv.txt" ```

**Comment by petergeneric** [comment]
@miller0929 were you able to get it working?

**Comment by petergeneric** [comment]
No response and I can't reproduce myself, so closing this issue. Feel free to comment if you're still having issues
