### ISSUE TITLE
Timestamp unset error

### ISSUE THREAD

**Issue by PigMan9080** [petergeneric/unifi-protect-remux#12]
First of all, great project, helped me out a lot.  Now I can just have a cron job and backup onto s3 for a cloud backup.

This is the error I'm getting.  I'm not sure if it's addressed or answered somewhere, ignore me if it is.
```Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly```

**Comment by TokugawaHeavyIndustries** [comment]
@PigMan9080 ffmpeg has been reporting that for years.  It should still be processing and outputting files.

**Comment by petergeneric** [comment]
Hi @PigMan9080 I'm glad you're finding it useful! @TokugawaHeavyIndustries hit the nail on the head here - there's no cause for alarm, that message is coming from FFmpeg (which is being called to remux the h264 bitstream into an MP4). FFmpeg has had that warning for years and there seems to be no plan to remove the logic (FFmpeg prioritises getting things working over strict correctness, so I doubt this logic will ever be removed).

These timestamps come from Ubiquiti, and since they use FFmpeg themselves to create MP4s, if that FFmpeg code did get removed I suspect that Ubiquiti would fix their timestamps. Failing that, in that eventuality I could write some logic to fix up the bitstreams before remuxing them.
