### ISSUE TITLE
Error parsing track

### ISSUE THREAD

**Issue by mikeyd1205** [petergeneric/unifi-protect-remux#13]
Having an error when running remux on x86 using qemu.  Command below.  Followed latest instructions for running remux on x86 hardware and dependencies are installed.

root@homeserver:/tmp# ./remux -with-audio=true /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv
2021/08/22 20:29:00 Analysing  /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv
2021/08/22 20:29:00 Error parsing track number!strconv.Atoi: parsing "--file=<filePath>": invalid syntax

**Comment by petergeneric** [comment]
Hi,

Can you send me the output of the following command please? 

`/usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo -P -f /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv | gzip -c info.txt.gz`

There's nothing confidential in this output

**Comment by mikeyd1205** [comment]
Well there is a problem, is that directory supposed to be there on my linux machine?  I did not see that in the instructions.

root@homeserver:/tmp# /usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo -P -f /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv | gzip -c info.txt.gz
-bash: /usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvinfo: No such file or directory

**Comment by petergeneric** [comment]
When you say that directory, do you mean /usr/share/unifi-protect/app/node_modules/.bin ? Alternatively do you have ubnt_ubvinfo on your path at all? If not you'll need to copy it across - the main readme does have instructions on how to do this: https://github.com/petergeneric/unifi-protect-remux (search for "ubnt_ubvinfo")

**Comment by mikeyd1205** [comment]
I have arm-ubnt_ubvinfo and ubnt_ubvinfo in /usr/bin.  Re-ran the command, got another error with gzip.

root@homeserver:/usr/bin# /usr/bin/ubnt_ubvinfo -P -f /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/7
4ACB9014479_0_rotating_1624606464418.ubv | gzip -c info.txt.gz
gzip: info.txt.gz: No such file or directory
At least one file path is mandatory

**Comment by petergeneric** [comment]
That's my mistake, it should be `| gzip -c > info.txt.gz`

**Comment by mikeyd1205** [comment]
root@homeserver:/usr/bin# /usr/bin/ubnt_ubvinfo -P -f /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv | gzip -c > info.txt.gz
At least one file path is mandatory

**Comment by petergeneric** [comment]
Perhaps it would be easier to remove the | gzip -c > info.txt.gz and just run the command initially, and make sure that you get output?

If you run it and do get output (it will likely be quite a large table output), can you capture it to a text file and send that?

**Comment by mikeyd1205** [comment]
This is weird.  It is not liking the file path with the ubnt_ubvinfo command. tried using --file="filepath" as well.  That directory is a mergerfs directory, but that shouldnt be causeing any issues.  Tried moving the file to temp just to make sure, same error.

root@homeserver:/usr/bin# ubnt_ubvinfo -f /srv/b3a0bb32-2db4-417e-b48a-69324bd7aee3/Media/Michael/unifi_video/2021/06/25/74ACB9014479_0_rotating_1624606464418.ubv
At least one file path is mandatory
usage: /usr/bin/arm-ubnt_ubvinfo <OPTIONS>

**Comment by petergeneric** [comment]
I wouldn't have expected them to be doing anything fancy or weird with file io, i assume stat and md5sum work fine on that file and stat doesn't report anything odd? My remux utility currently uses the output of that Ubiquiti tool to determine how to chop up the file, so you may need to play around a bit to figure out what's going on.

If you have any files that don't have sensitive information and you're comfortable sharing I can have a look at the .ubv files directly to make sure they're not corrupt - but I realise that may not be possible (the mac address of the camera is the first part of the filename, and the last part of the filename is a timestamp expressed in milliseconds since 1970 utc)

Another option if you have a replacement UDMP already is to transfer your old .ubv files to the UDMP, then run the ubnt_ubvinfo command on the UDMP - the remux tool does look for "filename.ubv.txt" and, if present, assumes that's the output of "ubnt_ubvinfo -P -f filename.ubv"

**Comment by petergeneric** [comment]
Looks to have been an issue with files on a snapraid array, remuxing worked fine on the OS drive - no further details on why the snapraid access wasn't working, so closing this issue
