### ISSUE TITLE
A few items getting started

### ISSUE THREAD

**Issue by davidcomtois** [petergeneric/unifi-protect-remux#23]
While getting started on a fresh Ubuntu 22.04.1 LTS install, I had to install go and make before being able to build the remux.go file

The ubnt_ubvinfo file I am using was retrieved from a UNVR with Protect version 2.1.2

When redirecting the executable to run as aarch64, I had to modify this line to point to the file intended to be input
WAS: exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo "\$@"
MODIFIED TO: exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo --file="$@"

By default, the ubnt_ubvinfo file will read the .ubv file and say there there is 0 partitions found and exit
Adding two rows of ----------- PARTITION START ----------- to the beginning of the text file, makes remux behave as designed and export the video file

**Comment by petergeneric** [comment]
Hi,

There are pre-built binaries in the 'releases' section on GitHub, but you can certainly build your own binary by installing Make & Go as you noted!

Strange you needed to make that modification to the ubnt_ubvinfo wrapper, the ubvinfo.go script passes the "-f" argument, so will need to check if it's an issue with qemu-aarch64 interpreting the "-f" argument as an arg to itself rather than the wrapped process.

Thanks for the report, and good you were able to get it working on your setup.
