### ISSUE TITLE
Error waiting for ubv: exit status 5

### ISSUE THREAD

**Issue by abenzick** [petergeneric/unifi-protect-remux#33]
Hello, running remux on WSL2 image on Windows 10. 

Verified ubnt_ubvinfo runs from command line and is in the /usr/bin folder
Verified ffmpeg is installed and runs from the command line

Running command line: ./remux *.ubv results in:
Error waiting for ubv: exit status 5

.ubv file is a_0_rotating_ source file. 

Probably a permission problem right?

**Comment by petergeneric** [comment]
Could be - this indicates that the `ubnt_ubvinfo` command failed to run against that .ubv file - there have been a number of reports like this for WSL, in all cases I think users were running against a .ubv file stored on their Windows drive mounted inside WSL. Can you try copying to an ext4 (or otherwise linux-native) filesystem and re-running?

If you do manage to get it running with the .ubv file on a Windows disk/share, let me know how because it'd help other folks using Windows!

**Comment by abenzick** [comment]
I was running it from a windows mounted drive. I just copied everything into the /usr/bin folder to test and am getting the same error. Suggestions on another folder to copy to?

This video is actually part of something interesting that's timely to review and we are restricted in options based on the circumstances of an investigation. 

There could be some user errors on my end. Hit me up offline and I can share more details.

**Comment by petergeneric** [comment]
If you are able to, the easiest thing might be to run the remux tool on Ubiquiti hardware, you just need to download the ARM static build of FFmpeg.

If you're getting exit code 5 on the ubnt_ubvinfo tool even with the .ubv in /usr/bin then that suggests to me the video file might be corrupt (or there's some weirdness going on with WSL2) - try running the following commands... basically if it doesn't work then the remux tool can't extract the video (I do have ways to recover partial content from a .ubv file, but that's a manual process).

```
ubnt_ubvinfo -p -f your-file.ubv
```

```
ubnt_ubvinfo -P -f your-file.ubv
```

If these both work then try writing their contents to your-file.ubv.txt - the remux tool will use that if present rather than running ubnt_ubvinfo.

P.S. another option if you're not able to load the remux tool onto your Ubiquiti hardware is to run ` /usr/share/unifi-protect/app/node_modules/.bin/ubnt_ubvexport -s your-file.ubv -d my_output_prefix` and see if that works - it doesn't seem to work as reliably on partial/corrupt files as my tool, but worth a try if ubnt_ubvinfo is failing on WSL2

**Comment by abenzick** [comment]
/usr/bin$ ubnt_ubvinfo -p -f B4FBE49EA3D9_0_rotating_1684832814509.ubv
----------------------
  fixed metadata: `dl . '>   N `
dynamic metadata: 40/0
        contents: 44/1073604572
     seek points: 433
       0. OFF: 44; WC: 1684832802935
       1. OFF: 2489892; WC: 1684832807963
it goes on through all the points and ends:
 432. OFF: 1071159452; WC: 1684834962972
:0 Shutting down the logger leaving you in the dark. Bye bye... :(

**Comment by abenzick** [comment]
Running with capital P

------------ PARTITION END ------------
:0 Malformed R123x packet
:0 Error occurred while parsing the file: (-2146697211)
Stats
Audio: frames: 101484; bytes: 17319936; minTs: 1684832803310; maxTs: 1684834968317; bitrate: 62.50kbps; mbday: 659.18 MB/day
Video: frames: 54125; bytes: 1052318813; minTs: 1684832802935; maxTs: 1684834967932; bitrate: 3797.35kbps; mbday: 40050.12 MB/day
:0 Shutting down the logger leaving you in the dark. Bye bye... :(
