### ISSUE TITLE
Need more help / clarification

### ISSUE THREAD

**Issue by TheHuffsta** [petergeneric/unifi-protect-remux#34]
I've been fiddling around with this for a while...I got it "working" but not sure it's actually working as intended as it seems to render about 10-20 videos that are all the same even though I've remuxed literally thousands of ubv's with all different names and in different folders (ie 2021/07/01, 2021/07/04 etc).

I'm using the latest version of Ubuntu. I have a HDD that was pulled from my UDMP 2ish years ago. I pulled the ubnt_ubvinfo from that drive and per the install guide I copied it to the usr/bin folder in Ubuntu (because I don't find a usr/bin/arm-ubnt_ubvinfo folder). After installing aarch64 copying and pasting this:

sudo tee /usr/bin/ubnt_ubvinfo <<EOF
#!/bin/sh
export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo "\$@"
EOF
chmod +x /usr/bin/ubnt_ubvinfo

It appears to do nothing. Am i supposed to run those 1 line at a time? I'm not a linux user by any means so perhaps I'm doing that wrong. When I try and remux after that I get a exit status 1. I also noticed that after running the above code that #1 the ubnt_ubvinfo file shrank from 4mb down to 110k. Additionally there is no arm-ubnt_ubvinfo that I can find in the usr/bin folder. I'm going mad here lol

**Comment by petergeneric** [comment]
What you want to do is write the `ubnt_ubvinfo` binary file that you pulled from the drive into `/usr/bin/arm-ubnt_ubvinfo` on your local system. This is because it can't be run directly on an x86 machine (because the Ubiquiti tool is written for ARM CPUs). The `tee` command above creates a wrapper program that sets up the QEMU ARM emulator & calls the arm-ubnt_ubvinfo command.

So literally just do this in the directory where you recovered that `ubnt_ubvinfo` binary from your Ubiquiti device's drive:
```
sudo cp ubnt_ubvinfo /usr/bin/arm-ubnt_ubvinfo
```

Next - the "tee" script you have above is the older, incorrect version, you'll need to use the following instead. Just copy the whole code block, paste it into your terminal and hit enter:

```
sudo tee /usr/bin/ubnt_ubvinfo <<EOF
#!/bin/sh
export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
exec qemu-aarch64 /usr/bin/arm-ubnt_ubvinfo "\$@"
EOF
chmod +x /usr/bin/ubnt_ubvinfo
```

You should then be able to run `remux` against a .ubv file.

**Comment by TheHuffsta** [comment]
Cool, that seems to have worked.

But so did whatever I did before lol...does it make any sense that I'd be seeing the same videos over and over again regardless of what folder they came from and what their file name was? I know the first part of the filename is the mac address of the camera, and one mac (a g3 instant) was muxing videos of a g4 bullet in my woods, or my doorbell, or a g3 dome...or the proper g3 instant...

**Comment by petergeneric** [comment]
To be frank, it doesn't make any sense - if you're running `remux` against a single .ubv and getting the same output as another .ubv that would suggest to me that the contents of those .ubv files are the same.

You could try putting each .ubv into its own folder and running `remux` on them individually - the resulting .mp4 outputs should be different. If they're the same even when things are in totally separate folders & running remux one-at-a-time then there must be something up with the .ubv files.

You can compare .ubv files to make sure their contents are different by using `md5sum file1 file2 file3...`, it will create a fingerprint of each file and display it... each file should have a different fingerprint

**Comment by TheHuffsta** [comment]
I would agree, but I just can't wrap my head around it...We are really looking for deleted clips. While cameras were set to record 24/7 a few clips were deleted. The drive was removed the same day so unlikely they were overwritten, but it is strange that footage from May 2021 say they were modified in July, even though the drive wasn't in use in July. I dunno. I'll remux everything again now that I feel it is setup correctly and see what happens. If I can figure out which files are identical I'll see what the md5sum shows.

Thanks for your prompt responses!

**Comment by petergeneric** [comment]
No, having the drive hooked up by USB is fine, and there's no SQL DB to worry about... the .ubv files are essentially just obfuscated self-contained MP4 files

The 'could not open /lib/ld-linux-aarch64.so.1' error is a bit more worrying, that suggests that the `qemu-user gcc-aarch64-linux-gnu` packages may not be installed correctly (or at least not as expected when I wrote the instructions).


Another option that you might want to consider is having a look at the URL in this line of  Pull Request 8: https://github.com/petergeneric/unifi-protect-remux/pull/8/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R14

I can't accept the Pull Request into this project because I'm not 100% confident that the file it references can be redistributed by people other than Ubiquiti, it's the x86 version of ubnt_ubvinfo that Ubiquiti released as part of earlier Protect test builds (before they opted to lock Protect down to their own hardware)... however you're free to make your own mind up independently whether this style of redistribution is permitted.

**Comment by TheHuffsta** [comment]
Ok, I pulled down that one as well as one off my current UDMP. Copied to /usr/bin and re-ran the code you posted above. This is what I get now:

chuff@chuff-virtual-machine:~/Remux$ ubnt_ubvinfo | head -n1
qemu-aarch64: /usr/bin/arm-ubnt_ubvinfo: Invalid ELF image for this architecture

and

chuff@chuff-virtual-machine:~/Remux$ '/home/chuff/Remux/remux' *.ubv
2023/06/02 13:35:29 Analysing  74ACB99E38D9_0_rotating_1625624516885.ubv
2023/06/02 13:35:29 Error waiting for ubv: exit status 255

For some reason I can't just run "remux", I have to do the full path, but I don't necessarily mind.

**Comment by TheHuffsta** [comment]
Oddly it works on 1 Ubuntu machine while the other throws errors, so I must have messed something up. I'll figure it out...It's taking about 3 min per file on the external drive. Is that about right or is my hdd the bottleneck?

**Comment by petergeneric** [comment]
The hard drive will always be the limiting factor with a remux - it's an IO-heavy process, very CPU-light - so the faster the connection to the drive the better!

Having source + destination on different drives is a good easy way to boost performance on these sorts of tasks, if possible

**Comment by TheHuffsta** [comment]
Everything is working great BTW...

I've been playing around with deleting clips and such. It appears, when a clip is deleted, it literally just removes the frames from the UBV. Any idea if there is a way to recover those frames?

**Comment by petergeneric** [comment]
I did look into this a while back, I'm pretty sure they're permanently gone (it might be possible to recover them from the free space on the drive shortly after they're removed, but that's a whole other ballgame better suited to a forensics company)

**Comment by TheHuffsta** [comment]
I don't want to beat a dead horse here, but you seem to be the only one with knowledge of these UBV files lol...The more I dig into these "deleted" clips and such, the more I think they AREN'T actually deleted. Wonder if you can offer some insight possibly or start a new project :-P 

To test, I walked through my kitchen and then deleted part of the video via web browser...verified in the video.deleted.log and quickly grabbed the UBV file associated. Remuxing indeed showed me disappear mid walk, and even though the UBV was 1.1gb it only remuxed at like 750mb, which makes me think the footage is still there but somewhere in the UBV properties it's told to ignore the frames that I deleted. Any thoughts on how to look at the UBV "properties" if you will?

**Comment by petergeneric** [comment]
I'm pretty sure I looked into this before and the relevant blocks holding the video frames were actually [deallocated](https://man7.org/linux/man-pages/man2/fallocate.2.html) from the .ubv... if you'd like to investigate this, can you try the following:

On your Ubiquiti device:
1. Pick a recording .ubv file
2. Run `stat file.ubv` on it
3. Delete some frames
4. Run `stat file.ubv` on it again

If my memory is correct, the `Blocks:` count reported after the deletion should be significantly reduced after the delete operation.
