### ISSUE TITLE
Simplifying automation / scripts 

### ISSUE THREAD

**Issue by briankhud** [petergeneric/unifi-protect-remux#42]
This isn't a bug, but an explanation of how I'm using the tool and some enhancements I've been playing with on my end.  I'm trying to figure out if I'm going about this the right way, or if there's another approach.

I've got some on-site storage and my ultimate goal is to get converted MP4 files over there reliably (including downtime of either the cloudkey or the on-site storage / networking). I have some scripts that can automatically generate MP4s, and others to copy the MP4 files from the cloudkey once created, but if I delete them once backed up, the automation I have will recreate them.

I thought about doing an existence check on the destination side first, but the file naming for each of the partitions makes it so that I don't know the filenames to check ahead of time. At first, I thought about computing these filenames manually in the script. Then realized that the unix time in milliseconds of the ubv filename doesn't line up with the start time of the partition necessarily - and of course if there's more than one in a UBV, there's no way to do this based on the filename alone. 

So then I decided to add a feature that creates <output-filename>.done in a file next to the converted MP4. This is somewhat nice, in that it allows me to skip the MP4 creation and doing the transfer. However, remux still enumerates the files on the cloudkey and does I/O to analyze the UBV partitions that I would like to prevent. So I also added a .done file on the source side once completing conversion so that I won't go back and convert again.

So after all my logic, I can run a script that scours everything on the cloudkey and quickly and efficiently skips converting UBV files if there's a corresponding .done file. In case of some issue on the cloudkey side (replacing drive, having to factory reset, etc etc...), the .done files on the destination end prevents duplicative processing if they've been converted in the past.

I know the .txt option exists, but I really don't want any of the logic for this data pipeline to have to live off of the cloudkey itself. I think my final setup will be an additional drive on the cloudkey where I put the MP4s and corresponding .done files, and I'll have my sync scripts just move the .MP4 files off of that drive (leaving the .done files) once they've been synced to their permanent location.

So with all that being said, I'd like to submit some improvements to make my workflow easier and share them with others, but I'm new to all this (scripting, Go, etc...), so I wanted to bounce my approach off others.

I've so far added a -output-listing <filename> option which creates a file marking the operation as done (and only if the MP4 itself is created). Setting this to "SRC-NAME" automatically names the file the same thing as the MP4 but instead with a .done extension.

I haven't created a new option on the source side - while I put this in the tool for now, I could probably put this in my processing script instead. Thoughts on the approach here and the behaviors I've added?

**Comment by petergeneric** [comment]
That sounds like a perfectly reasonable approach given how you want it to work. Personally I'd be inclined to keep the `output-listing` capability in scripts rather than in Go (simply because shell is great at working with the filesystem). One thought would be a shell script that wraps `remux` that will process one or more .ubv files passed in as arguments, and if successfully demuxed will delete the .ubv and create the equivalent .done file (or you could even rename the .ubv to .done, and then periodically use `truncate` to empty the .ubv file - this way you'd be able to hold on to the originals for a while in the event of any problems.

If you're new to shell scripting and planning to release the scripts, I'd also recommend running your scripts through [shellcheck](https://www.shellcheck.net/) to catch any subtle bugs or non-portable behaviours.


P.S. since I wrote `remux`, Ubiquiti has started shipping `ubnt_ubvexport` with Protect, and you may wish to wrap this instead - give it a go, it seems reasonably good (although I still think there are cases where my tool can help recover frames from corrupted files)


As an aside, I used to do something similar, but instead I transferred and kept the .ubv files (I like to keep originals as the archived media, rather than converted files -- and I also wanted to run all IO-intensive operations on server hardware rather than the fairly IO-limited cloudkey). Because I was transferring the .ubv files, I was able to use rsync to pull them onto to my server & it would automatically handle pulling across only new/changed files. Any time a .MP4 was required, it was easy to generate on the fly given the much larger IO capabilities of my server vs the cloudkey (I used the x86 version of ubnt_ubvinfo, but it would work just as well with the qemu wrapper).

**Comment by briankhud** [comment]
Thanks @petergeneric - for your suggestion, I'm still not sure how to deal with the fact that I don't know what file names the tool will create prior to running it, so there's no elegant way to know what to delete after transfer.

I had tried rsync as well, but found the filtering syntax to be really unintuitive. I ended up using SyncThing - but I'll admit that's a lot of extra software running, especially given how admin for it works and the nature of the data.

I'll check out ubvinfo and (new!) ubvexport tool and see if an approach for solving the file name is available.

**Comment by petergeneric** [comment]
I don't think ubvexport has an option for that, but I'd be inclined to extract to a dedicated folder rather than worrying about the exact output filenames? Good luck anyway! Feel free to drop a comment on this ticket if/when you decide to release your scripts
